# Generated by Django 5.2 on 2025-04-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='order_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
