# Generated by Django 5.2 on 2025-05-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_image_lesson_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення (URL)'), ('video', 'Відео (YouTube URL)'), ('file', 'Файл (PDF, DOCX, тощо)'), ('link', 'Посилання')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
